WebUI/Controllers/BookTicketController.cs
using Models.DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebAPI.Helpers;

namespace WebUI.Controllers
{
    public class BookTicketController : Controller
    {
        readonly Constants constants = new Constants();
        HttpClient hc = new HttpClient
        {
            BaseAddress = new Uri(ConfigurationManager.AppSettings["WebAPIURL"].ToString())
        };

        public ActionResult Index()
        {
            List<MovieDetails> objList = new List<MovieDetails>();
            objList = GetMovieDetailsList();
            return View(objList);
        }

        public ActionResult MovieDetails(string MovieName)
        {
            var MovieDetails = new MovieDetails();

            var responseTask = hc.GetAsync("API/BookTicket/GetMovieDetails/" + MovieName);
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<MovieDetails>();
                readResult.Wait();
                MovieDetails = readResult.Result;
            }
            return View(MovieDetails);
        }

        public ActionResult BookTicket(int MovieID)
        {
            var MovieDetails = new MovieDetails();

            MovieDetails = GetMovieDetailsList().Where(a => a.MovieID == MovieID).FirstOrDefault();

            return View(MovieDetails);
        }

        public ActionResult SelectSeats(int ScreenTimingConfigID )
        {
            MovieBooking movieBooking = new MovieBooking();
            movieBooking.ScreenTimingConfigID_FK = ScreenTimingConfigID;
            movieBooking.screenDetail = GetScreenDetails(ScreenTimingConfigID);
            movieBooking.lstSeatCategory = new List<CommonDropDown>();
            movieBooking.lstSeatCategory = GetSeatCategory();
            movieBooking.hdnAlreadySelectedSeats = GetAlreadySelectedSeatsForScreenConfigID(movieBooking.ScreenTimingConfigID_FK);

            return PartialView(movieBooking);
        }

        public List<CommonDropDown> GetTimings()
        {
            var timingList = new List<CommonDropDown>();

            var responseTask = hc.GetAsync("API/BookTicket/GetTimings");
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<List<CommonDropDown>>();
                readResult.Wait();
                timingList = readResult.Result;
            }
            return timingList;
        }

        public List<MovieScreenTimingConfig> GetMovieScreenTimingConfig(int MovieID)
        {
            List<MovieScreenTimingConfig> lstMovieScreenTimingConfig = new List<MovieScreenTimingConfig>();

            var responseTask = hc.GetAsync("API/BookTicket/GetMovieScreenTimingConfig/" + MovieID);
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<List<MovieScreenTimingConfig>>();
                readResult.Wait();
                lstMovieScreenTimingConfig = readResult.Result;
            }
            return lstMovieScreenTimingConfig;

        }

        public List<MovieDetails> GetMovieDetailsList()
        {
            var MovieList = new List<MovieDetails>();

            var responseTask = hc.GetAsync("API/BookTicket/GetMovieDetailsList");
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<List<MovieDetails>>();
                readResult.Wait();
                MovieList = readResult.Result;
            }
            return MovieList;
        }

        public List<CommonDropDown> GetSeatCategory()
        {
            var timingList = new List<CommonDropDown>();

            var responseTask = hc.GetAsync("API/BookTicket/GetSeatCategory");
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<List<CommonDropDown>>();
                readResult.Wait();
                timingList = readResult.Result;
            }
            return timingList;
        }

        public ScreenDetail GetScreenDetails(int ScreenTimingConfigID)
        {
            ScreenDetail screenDetail = new ScreenDetail();

            var responseTask = hc.GetAsync("API/BookTicket/GetScreenDetails/" + ScreenTimingConfigID);
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<ScreenDetail>();
                readResult.Wait();
                screenDetail = readResult.Result;
            }

            return screenDetail;
        }

        public string GetAlreadySelectedSeatsForScreenConfigID(int ScreenConfigID)
        {
            string hdnAlreadySelectedSeats = "";
            var responseTask = hc.GetAsync("API/BookTicket/GetAlreadySelectedSeatsForScreenConfigID/" + ScreenConfigID);
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsStringAsync();
                readResult.Wait();
                hdnAlreadySelectedSeats = readResult.Result;
            }

            return hdnAlreadySelectedSeats;
        }

        public ActionResult TheatreDetails(string id = null)
        {
            if (!string.IsNullOrEmpty(id))
            {
                TheaterDetails theaterDetail = new TheaterDetails();

                var responseTask = hc.GetAsync("API/BookTicket/GetTheatreDetailsByID/" + id);
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readResult = result.Content.ReadAsAsync<TheaterDetails>();
                    readResult.Wait();
                    theaterDetail = readResult.Result;
                }

                return View("TheatreDetails", theaterDetail);
            }
            else
            {
                List<TheaterDetails> listTheatreDetail = new List<TheaterDetails>();

                var responseTask = hc.GetAsync("API/BookTicket/GetUsersTheatreDetails/" + User.Identity.Name);
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readResult = result.Content.ReadAsAsync<List<TheaterDetails>>();
                    readResult.Wait();
                    listTheatreDetail = readResult.Result;
                }

                return View("UsersTheatreDetails", listTheatreDetail);
            }
        }

        public ActionResult AddTheatreDetails()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTheatreDetails(TheaterDetails obj, HttpPostedFileBase imgFile)
        {
            obj.UserName_FK = User.Identity.Name;

            string path = "";
            Random random = new Random();
            int rnd = random.Next(1000, 9999);
            if (imgFile != null && imgFile.ContentLength > 0)
            {
                string ext = Path.GetExtension(imgFile.FileName);
                {
                    if (ext.ToLower().Equals(".jpg") || ext.ToLower().Equals(".jpeg") || ext.ToLower().Equals(".png"))
                    {
                        try
                        {
                            string tempFileName = User.Identity.Name + "-" + obj.Name.Replace(" ", "") + "-" + rnd + ext;
                            path = Path.Combine(Server.MapPath(constants.TheatreImagePath), tempFileName);
                            imgFile.SaveAs(path);
                            path = constants.TheatreImagePath + "/" + tempFileName;
                        }
                        catch (Exception ex)
                        {
                            ModelState.AddModelError("", "Some Error Occured While Saving the Image.( " + ex.Message + " )");
                            return View(obj);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Only .JPG, .JPEG, .PNG format is allowed.");
                        return View(obj);
                    }
                }
            }

            obj.ImgPath = path;

            var responseTask = hc.PostAsJsonAsync<TheaterDetails>("API/BookTicket/AddTheatreDetails", obj);
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                ViewBag.Message = "Theatre Added Succesfully..!";
                ViewBag.Link = constants.MyTheatreURL;
                ViewBag.ButtonName = "Close";
                return View("CommonValidationPrinter");
            }

            ViewBag.Message = "Theatre Additon Failed.!";
            return View();
        }

        public ActionResult ScreenDetails(int id)
        {
            ScreenDetail screen = new ScreenDetail();

            var responseTask = hc.GetAsync("API/BookTicket/GetScreenDetailByID/" + id.ToString());
            responseTask.Wait();
            var result = responseTask.Result;

            if (result.IsSuccessStatusCode)
            {
                var readResult = result.Content.ReadAsAsync<ScreenDetail>();

WebUI/Views/BookTicket/AddMovieToTheatre.cshtml
@model Models.DTO.MovieDetails

@{
    ViewBag.Title = "AddProduct";
}

@using (Html.BeginForm("AddProduct", "Products", FormMethod.Post, new {enctype = "multipart/form-data", @class = "addProduct_Form" }))
{
    @Html.AntiForgeryToken()

<div class="addProduct_Form_Div">
    <h2>Add Theatre</h2>
    @Html.ValidationSummary(true, "", new { @class = "text-danger", @id = "txtValidationSummary" })

    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model., new { htmlAttributes = new { @class = "form_Control", @placeholder = "Name", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.PTitle, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Title", @required = "required" } })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input full_Address">
            @Html.TextAreaFor(model => model.PDescription, new { @class = "form_Control", @rows = "4", @cols = "100", @placeholder = "Description", @required = "required" })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Quantity", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Price", @required = "required" } })
        </div>
    </div>

    <div class="row_Input">
        <input type="file" name="imgFile" class="login_Submit" onchange="getImagePreview(event)" />
        <div class="form_Input">
            @Html.DropDownListFor(model => model.CategoryID_FK, new SelectList(ViewBag.CategoryList, "Value", "Text"), "Please Select Category", new { @class = "form_Control", @placeholder = "Select Category", @required = "required" })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input hidden" id="imgPreview"></div>
    </div>

    <button type="submit" class="login_Submit">Add Product</button>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

WebUI/Views/BookTicket/AddNewScreen.cshtml
@model Models.DTO.ScreenDetail

@{
    ViewBag.Title = "Add New Screen";
}

@using (Html.BeginForm("AddNewScreen", "BookTicket", FormMethod.Post, new {@class = "addProduct_Form" }))
{
    @Html.AntiForgeryToken()

<div class="addProduct_Form_Div">
    <h2>Add Screen</h2>
    @Html.ValidationSummary(true, "", new { @class = "text-danger", @id = "txtValidationSummary" })
    @Html.HiddenFor(model=>model.TheaterID_FK)
    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model.PriceRecliner, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Price for Recliner", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.NoOfSeatsRecliner, new { htmlAttributes = new { @class = "form_Control", @placeholder = "No Of Seats for Recliner", @required = "required", @type = "number" } })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model.PricePlatinum, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Price for Platinum", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.NoOfSeatsPlatinum, new { htmlAttributes = new { @class = "form_Control", @placeholder = "No Of Seats for Platinum", @required = "required", @type = "number" } })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model.PriceGold, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Price for Gold", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.NoOfSeatsGold, new { htmlAttributes = new { @class = "form_Control", @placeholder = "No Of Seats for Gold", @required = "required", @type = "number" } })
        </div>
    </div>

    <div class="row_Input">
        <div class="form_Input">
            @Html.EditorFor(model => model.PriceSilver, new { htmlAttributes = new { @class = "form_Control", @placeholder = "Price for Silver", @required = "required" } })
        </div>

        <div class="form_Input">
            @Html.EditorFor(model => model.NoOfSeatsSilver, new { htmlAttributes = new { @class = "form_Control", @placeholder = "No Of Seats for Silver", @required = "required", @type = "number" } })
        </div>
    </div>

    <button type="submit" class="login_Submit">Add</button>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebUI/Views/BookTicket/AddTheatreDetails.cshtml
@model Models.DTO.TheaterDetails

@{
    ViewBag.Title = "Add Theatre Details";
}

<div class="add-theatre-main-container">
    <div class="add-theatre-card">
        <div class="add-theatre-header">
            <i class="fa fa-film"></i>
            <h2>Add Theatre</h2>
        </div>
        @using (Html.BeginForm("AddTheatreDetails", "BookTicket", FormMethod.Post, new {enctype = "multipart/form-data", @class = "add-theatre-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger", @id = "txtValidationSummary" })
            <div class="add-theatre-form-grid">
                <div class="form-group">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-input", @placeholder = "Name", @required = "required" } })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.NoOfScreens, new { htmlAttributes = new { @class = "form-input", @placeholder = "No. of Screens", @required = "required", @type = "number" } })
                </div>
                <div class="form-group full-width">
                    @Html.TextAreaFor(model => model.Location, new { @class = "form-input", @rows = "3", @placeholder = "Location", @required = "required" })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.Landmark, new { htmlAttributes = new { @class = "form-input", @placeholder = "Landmark", @required = "required" } })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-input", @placeholder = "Pincode", @required = "required", @type = "number" } })
                </div>
                <div class="form-group full-width">
                    <input type="file" name="imgFile" class="form-input file-input" onchange="getImagePreview(event)" />
                </div>
                <div class="form-group full-width">
                    <div class="form-input hidden" id="imgPreview"></div>
                </div>
            </div>
            <button type="submit" class="add-theatre-btn"><i class="fas fa-plus-circle"></i> Add Theatre</button>
        }
        <div class="add-theatre-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "back-btn" })
        </div>
    </div>
</div>

<style>
.add-theatre-main-container {
    width: 94%;
    margin: 40px auto;
    padding: 0 10px;
    display: flex;
    justify-content: center;
}
.add-theatre-card {
    background: #fff;
    border-radius: 18px;
    box-shadow: 0 4px 24px rgba(0,0,0,0.10);
    padding: 0 0 32px 0;
    max-width: 520px;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: stretch;
}
.add-theatre-header {
    background: linear-gradient(135deg, #252525, #34495e);
    color: #fff;
    border-radius: 18px 18px 0 0;
    padding: 32px 32px 20px 32px;
    display: flex;
    align-items: center;
    gap: 16px;
}
.add-theatre-header h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0;
    display: flex;
    align-items: center;
    gap: 12px;
}
.add-theatre-header i {
    color: #3498db;
    font-size: 2rem;
}
.add-theatre-form {
    width: 100%;
    padding: 32px 32px 0 32px;
    display: flex;
    flex-direction: column;
    gap: 18px;
}
.add-theatre-form-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 18px 18px;
    margin-bottom: 18px;
}
.form-group {
    display: flex;
    flex-direction: column;
    gap: 6px;
}
.full-width {
    grid-column: 1 / -1;
}
.form-input {
    width: 100%;
    padding: 12px 16px;
    border: 2px solid #e9ecef;
    border-radius: 8px;
    font-size: 16px;
    transition: all 0.3s ease;
    background: #fff;
    margin-bottom: 4px;
}
.form-input:focus {
    outline: none;
    border-color: #3498db;
    box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.1);
}
.file-input {
    padding: 8px 0 8px 0;
    background: #f8f9fa;
    border: none;
}
.add-theatre-btn {
    background: linear-gradient(135deg, #3498db, #2980b9);
    color: #fff;
    border: none;
    padding: 14px 0;
    border-radius: 8px;
    font-size: 18px;
    font-weight: 700;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    box-shadow: 0 2px 8px rgba(52, 152, 219, 0.12);
    margin: 0 32px;
}
.add-theatre-btn:hover {
    background: linear-gradient(135deg, #2980b9, #1f5f8b);
    transform: translateY(-2px);
}
.back-btn {
    background: #f8f9fa;
    color: #3498db;
    border: none;
    padding: 10px 18px;
    border-radius: 8px;
    font-size: 15px;
    font-weight: 600;
    transition: all 0.2s;
    box-shadow: 0 2px 8px rgba(52, 152, 219, 0.12);
    text-decoration: none;
    margin-top: 18px;
    margin-left: 32px;
    width: fit-content;
}
.back-btn:hover {
    background: #3498db;
    color: #fff;
}
.add-theatre-footer {
    display: flex;
    justify-content: flex-end;
    margin-top: 8px;
}
@@media (max-width: 700px) {
    .add-theatre-header {
        padding: 18px 10px 10px 10px;
        font-size: 1.1rem;
    }
    .add-theatre-header h2 {
        font-size: 1.1rem;
    }
    .add-theatre-form {
        padding: 16px 8px 0 8px;
    }
    .add-theatre-card {
        padding: 0 0 12px 0;
    }
    .add-theatre-btn {
        margin: 0 8px;
        font-size: 16px;
    }
    .back-btn {
        margin-left: 8px;
    }
    .add-theatre-form-grid {
        grid-template-columns: 1fr;
        gap: 12px 0;
    }
}
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebUI/Views/BookTicket/Index.cshtml
@model List<Models.DTO.MovieDetails>
@{
    ViewBag.Title = "Movie Tickets";
}

<div class="movie-booking-container">
    <div class="movie-booking-header">
        <i class="fas fa-film"></i>
        <h2>Book Movie Tickets</h2>
    </div>

    <div class="offer-banner">
        <div class="offer-banner-content">
            <i class="fas fa-star"></i>
            <h3>Special Offers</h3>
            <p>Get the best deals on movie tickets</p>
        </div>
    </div>

    <div class="movies-section">
        <h3 class="section-title">Recommended Movies</h3>
        <div class="movies-grid">
            @foreach (var mov in Model)
            {
                <div class="movie-card">
                    @Html.HiddenFor(a => mov.MovieID)
                    
                    <div class="movie-image-container">
                        @if (!string.IsNullOrEmpty(mov.ImgPath))
                        {
                            <a href="/BookTicket/MovieDetails?MovieName=@mov.MovieName">
                                <img src="@Url.Content(mov.ImgPath)" alt="@mov.MovieName" class="movie-image">
                            </a>
                        }
                        else
                        {
                            <a href="/BookTicket/MovieDetails?MovieName=@mov.MovieName">
                                <img src="~/Content/Images/Product.png" alt="@mov.MovieName" class="movie-image">
                            </a>
                        }
                        <div class="movie-overlay">
                            <button class="book-now-btn" onclick="window.location.href='/BookTicket/MovieDetails?MovieName=@mov.MovieName'">
                                <i class="fas fa-ticket-alt"></i> Book Now
                            </button>
                        </div>
                    </div>
                    
                    <div class="movie-info">
                        <h4 class="movie-title">@mov.MovieName</h4>
                        <p class="movie-description">@mov.Description</p>
                        <div class="movie-duration">
                            <i class="fas fa-clock"></i>
                            <span>@mov.Duration mins</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<style>
.movie-booking-container {
    width: 94%;
    margin: 40px auto;
    padding: 0 10px;
}

.movie-booking-header {
    background: linear-gradient(135deg, #252525, #34495e);
    color: #fff;
    padding: 32px 32px 20px 32px;
    border-radius: 18px 18px 0 0;
    display: flex;
    align-items: center;
    gap: 18px;
    margin-bottom: 24px;
}

.movie-booking-header i {
    font-size: 32px;
    color: #3498db;
}

.movie-booking-header h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0;
}

.offer-banner {
    background: linear-gradient(135deg, #3498db, #2980b9);
    border-radius: 12px;
    padding: 24px;
    margin-bottom: 32px;
    color: #fff;
    box-shadow: 0 4px 16px rgba(52, 152, 219, 0.3);
}

.offer-banner-content {
    display: flex;
    align-items: center;
    gap: 16px;
}

.offer-banner-content i {
    font-size: 24px;
    color: #f8c146;
}

.offer-banner-content h3 {
    font-size: 1.5rem;
    font-weight: 700;
    margin: 0;
}

.offer-banner-content p {
    margin: 4px 0 0 0;
    opacity: 0.9;
}

.movies-section {
    background: #fff;
    border-radius: 18px;
    padding: 32px;
    box-shadow: 0 4px 24px rgba(0,0,0,0.10);
}

.section-title {
    font-size: 1.8rem;
    font-weight: 700;
    color: #2c3e50;
    margin-bottom: 24px;
    display: flex;
    align-items: center;
    gap: 12px;
}

.section-title::before {
    content: '';
    width: 4px;
    height: 24px;
    background: linear-gradient(135deg, #3498db, #2980b9);
    border-radius: 2px;
}

.movies-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 24px;
}

.movie-card {
    background: #fff;
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 4px 16px rgba(0,0,0,0.08);
    transition: all 0.3s ease;
    border: 1px solid #e9ecef;
}

.movie-card:hover {
    transform: translateY(-8px);
    box-shadow: 0 8px 32px rgba(0,0,0,0.15);
}

.movie-image-container {
    position: relative;
    overflow: hidden;
}

.movie-image {
    width: 100%;
    height: 320px;
    object-fit: cover;
    transition: transform 0.3s ease;
}

.movie-card:hover .movie-image {
    transform: scale(1.05);
}

.movie-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.movie-card:hover .movie-overlay {
    opacity: 1;
}

.book-now-btn {
    background: linear-gradient(135deg, #3498db, #2980b9);
    color: #fff;
    border: none;
    padding: 12px 24px;
    border-radius: 8px;
    font-size: 16px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    gap: 8px;
    box-shadow: 0 4px 12px rgba(52, 152, 219, 0.3);
}

.book-now-btn:hover {
    background: linear-gradient(135deg, #2980b9, #1f5f8b);
    transform: translateY(-2px);
}

.movie-info {
    padding: 20px;
}

.movie-title {
    font-size: 18px;
    font-weight: 700;
    color: #2c3e50;
    margin: 0 0 8px 0;
    line-height: 1.3;
}

.movie-description {
    font-size: 14px;
    color: #7f8c8d;
    margin: 0 0 12px 0;
    line-height: 1.4;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
}

.movie-duration {
    display: flex;
    align-items: center;
    gap: 6px;
    color: #3498db;
    font-size: 14px;
    font-weight: 600;
}

.movie-duration i {
    font-size: 12px;
}

@@media (max-width: 768px) {
    .movie-booking-header {
        padding: 20px 20px 12px 20px;
        border-radius: 12px 12px 0 0;
    }
    
    .movie-booking-header h2 {
        font-size: 1.5rem;
    }
    
    .movies-section {
        padding: 20px;
        border-radius: 12px;
    }
    
    .section-title {
        font-size: 1.4rem;
    }
    
    .movies-grid {
        grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
        gap: 16px;
    }
    
    .movie-image {
        height: 280px;
    }
}

@@media (max-width: 480px) {
    .movie-booking-container {
        width: 96%;
        margin: 20px auto;
    }
    
    .movie-booking-header {
        padding: 16px 16px 8px 16px;
    }
    
    .movie-booking-header h2 {
        font-size: 1.2rem;
    }
    
    .movies-section {
        padding: 16px;
    }
    
    .movies-grid {
        grid-template-columns: 1fr;
        gap: 12px;
    }
    
    .movie-image {
        height: 240px;
    }
}
</style>